// =====================================================================
//  Daftar kata kerja tidak beraturan (Irregular Verbs) Bahasa Inggris.
//  Format tiap entri: { v1, v2, v3, arti }
//    v1   = bentuk dasar (base form)
//    v2   = bentuk lampau (past simple)
//    v3   = bentuk past participle
//    arti = makna dalam Bahasa Indonesia (disembunyikan secara default)
//
//  Bentuk yang punya dua varian ditulis dengan tanda "/" (mis. burnt/burned).
//  URUTAN: dari kata kerja yang PALING SERING dipakai -> paling jarang.
// =====================================================================

const IRREGULAR_VERBS = [
  { v1: "be", v2: "was/were", v3: "been", arti: "adalah; menjadi" },
  { v1: "have", v2: "had", v3: "had", arti: "memiliki; punya" },
  { v1: "do", v2: "did", v3: "done", arti: "melakukan" },
  { v1: "say", v2: "said", v3: "said", arti: "berkata" },
  { v1: "go", v2: "went", v3: "gone", arti: "pergi" },
  { v1: "get", v2: "got", v3: "gotten/got", arti: "mendapatkan" },
  { v1: "make", v2: "made", v3: "made", arti: "membuat" },
  { v1: "know", v2: "knew", v3: "known", arti: "mengetahui" },
  { v1: "think", v2: "thought", v3: "thought", arti: "berpikir" },
  { v1: "take", v2: "took", v3: "taken", arti: "mengambil" },
  { v1: "see", v2: "saw", v3: "seen", arti: "melihat" },
  { v1: "come", v2: "came", v3: "come", arti: "datang" },
  { v1: "find", v2: "found", v3: "found", arti: "menemukan" },
  { v1: "give", v2: "gave", v3: "given", arti: "memberi" },
  { v1: "tell", v2: "told", v3: "told", arti: "memberitahu" },
  { v1: "feel", v2: "felt", v3: "felt", arti: "merasa" },
  { v1: "become", v2: "became", v3: "become", arti: "menjadi" },
  { v1: "leave", v2: "left", v3: "left", arti: "meninggalkan; pergi" },
  { v1: "put", v2: "put", v3: "put", arti: "meletakkan" },
  { v1: "mean", v2: "meant", v3: "meant", arti: "berarti; bermaksud" },
  { v1: "keep", v2: "kept", v3: "kept", arti: "menyimpan; menjaga" },
  { v1: "let", v2: "let", v3: "let", arti: "membiarkan; mengizinkan" },
  { v1: "begin", v2: "began", v3: "begun", arti: "memulai" },
  { v1: "show", v2: "showed", v3: "shown/showed", arti: "menunjukkan" },
  { v1: "hear", v2: "heard", v3: "heard", arti: "mendengar" },
  { v1: "run", v2: "ran", v3: "run", arti: "berlari" },
  { v1: "bring", v2: "brought", v3: "brought", arti: "membawa" },
  { v1: "write", v2: "wrote", v3: "written", arti: "menulis" },
  { v1: "sit", v2: "sat", v3: "sat", arti: "duduk" },
  { v1: "stand", v2: "stood", v3: "stood", arti: "berdiri" },
  { v1: "lose", v2: "lost", v3: "lost", arti: "kehilangan; kalah" },
  { v1: "pay", v2: "paid", v3: "paid", arti: "membayar" },
  { v1: "meet", v2: "met", v3: "met", arti: "bertemu" },
  { v1: "set", v2: "set", v3: "set", arti: "mengatur; menetapkan" },
  { v1: "learn", v2: "learnt/learned", v3: "learnt/learned", arti: "belajar" },
  { v1: "lead", v2: "led", v3: "led", arti: "memimpin" },
  { v1: "understand", v2: "understood", v3: "understood", arti: "memahami" },
  { v1: "speak", v2: "spoke", v3: "spoken", arti: "berbicara" },
  { v1: "read", v2: "read", v3: "read", arti: "membaca" },
  { v1: "spend", v2: "spent", v3: "spent", arti: "menghabiskan; membelanjakan" },
  { v1: "grow", v2: "grew", v3: "grown", arti: "tumbuh" },
  { v1: "win", v2: "won", v3: "won", arti: "menang" },
  { v1: "teach", v2: "taught", v3: "taught", arti: "mengajar" },
  { v1: "buy", v2: "bought", v3: "bought", arti: "membeli" },
  { v1: "send", v2: "sent", v3: "sent", arti: "mengirim" },
  { v1: "build", v2: "built", v3: "built", arti: "membangun" },
  { v1: "fall", v2: "fell", v3: "fallen", arti: "jatuh" },
  { v1: "cut", v2: "cut", v3: "cut", arti: "memotong" },
  { v1: "sell", v2: "sold", v3: "sold", arti: "menjual" },
  { v1: "break", v2: "broke", v3: "broken", arti: "mematahkan; memecahkan" },
  { v1: "hold", v2: "held", v3: "held", arti: "memegang" },
  { v1: "catch", v2: "caught", v3: "caught", arti: "menangkap" },
  { v1: "draw", v2: "drew", v3: "drawn", arti: "menggambar; menarik" },
  { v1: "choose", v2: "chose", v3: "chosen", arti: "memilih" },
  { v1: "eat", v2: "ate", v3: "eaten", arti: "makan" },
  { v1: "drive", v2: "drove", v3: "driven", arti: "mengemudi" },
  { v1: "hit", v2: "hit", v3: "hit", arti: "memukul; mengenai" },
  { v1: "throw", v2: "threw", v3: "thrown", arti: "melempar" },
  { v1: "fly", v2: "flew", v3: "flown", arti: "terbang" },
  { v1: "drink", v2: "drank", v3: "drunk", arti: "minum" },
  { v1: "sing", v2: "sang", v3: "sung", arti: "bernyanyi" },
  { v1: "swim", v2: "swam", v3: "swum", arti: "berenang" },
  { v1: "sleep", v2: "slept", v3: "slept", arti: "tidur" },
  { v1: "wear", v2: "wore", v3: "worn", arti: "memakai (pakaian)" },
  { v1: "hang", v2: "hung", v3: "hung", arti: "menggantung" },
  { v1: "forget", v2: "forgot", v3: "forgotten", arti: "lupa" },
  { v1: "shut", v2: "shut", v3: "shut", arti: "menutup" },
  { v1: "cost", v2: "cost", v3: "cost", arti: "berharga (seharga)" },
  { v1: "beat", v2: "beat", v3: "beaten", arti: "memukul; mengalahkan" },
  { v1: "lie", v2: "lay", v3: "lain", arti: "berbaring" },
  { v1: "lay", v2: "laid", v3: "laid", arti: "meletakkan" },
  { v1: "bite", v2: "bit", v3: "bitten", arti: "menggigit" },
  { v1: "blow", v2: "blew", v3: "blown", arti: "meniup" },
  { v1: "burn", v2: "burnt/burned", v3: "burnt/burned", arti: "membakar" },
  { v1: "deal", v2: "dealt", v3: "dealt", arti: "menangani; berurusan" },
  { v1: "dig", v2: "dug", v3: "dug", arti: "menggali" },
  { v1: "dream", v2: "dreamt/dreamed", v3: "dreamt/dreamed", arti: "bermimpi" },
  { v1: "fight", v2: "fought", v3: "fought", arti: "bertarung" },
  { v1: "forgive", v2: "forgave", v3: "forgiven", arti: "memaafkan" },
  { v1: "freeze", v2: "froze", v3: "frozen", arti: "membeku" },
  { v1: "hide", v2: "hid", v3: "hidden", arti: "menyembunyikan" },
  { v1: "hurt", v2: "hurt", v3: "hurt", arti: "melukai; menyakiti" },
  { v1: "lend", v2: "lent", v3: "lent", arti: "meminjamkan" },
  { v1: "light", v2: "lit/lighted", v3: "lit/lighted", arti: "menyalakan" },
  { v1: "quit", v2: "quit", v3: "quit", arti: "berhenti" },
  { v1: "ride", v2: "rode", v3: "ridden", arti: "menunggangi; mengendarai" },
  { v1: "ring", v2: "rang", v3: "rung", arti: "berdering; menelepon" },
  { v1: "rise", v2: "rose", v3: "risen", arti: "naik; terbit" },
  { v1: "seek", v2: "sought", v3: "sought", arti: "mencari" },
  { v1: "shake", v2: "shook", v3: "shaken", arti: "mengguncang" },
  { v1: "shine", v2: "shone", v3: "shone", arti: "bersinar" },
  { v1: "shoot", v2: "shot", v3: "shot", arti: "menembak" },
  { v1: "spread", v2: "spread", v3: "spread", arti: "menyebar" },
  { v1: "steal", v2: "stole", v3: "stolen", arti: "mencuri" },
  { v1: "stick", v2: "stuck", v3: "stuck", arti: "menempel; menusuk" },
  { v1: "sweep", v2: "swept", v3: "swept", arti: "menyapu" },
  { v1: "swing", v2: "swung", v3: "swung", arti: "berayun" },
  { v1: "swear", v2: "swore", v3: "sworn", arti: "bersumpah" },
  { v1: "tear", v2: "tore", v3: "torn", arti: "merobek" },
  { v1: "wake", v2: "woke", v3: "woken", arti: "bangun; membangunkan" },
  { v1: "wind", v2: "wound", v3: "wound", arti: "memutar; melilit" },
  { v1: "bend", v2: "bent", v3: "bent", arti: "membengkokkan" },
  { v1: "bet", v2: "bet", v3: "bet", arti: "bertaruh" },
  { v1: "bind", v2: "bound", v3: "bound", arti: "mengikat" },
  { v1: "bleed", v2: "bled", v3: "bled", arti: "berdarah" },
  { v1: "breed", v2: "bred", v3: "bred", arti: "membiakkan" },
  { v1: "burst", v2: "burst", v3: "burst", arti: "meledak; pecah" },
  { v1: "cast", v2: "cast", v3: "cast", arti: "melemparkan" },
  { v1: "cling", v2: "clung", v3: "clung", arti: "berpegang erat" },
  { v1: "creep", v2: "crept", v3: "crept", arti: "merayap; mengendap" },
  { v1: "feed", v2: "fed", v3: "fed", arti: "memberi makan" },
  { v1: "flee", v2: "fled", v3: "fled", arti: "melarikan diri" },
  { v1: "fling", v2: "flung", v3: "flung", arti: "melempar (kuat)" },
  { v1: "grind", v2: "ground", v3: "ground", arti: "menggiling" },
  { v1: "lean", v2: "leant/leaned", v3: "leant/leaned", arti: "bersandar" },
  { v1: "leap", v2: "leapt/leaped", v3: "leapt/leaped", arti: "melompat" },
  { v1: "mistake", v2: "mistook", v3: "mistaken", arti: "keliru; salah mengira" },
  { v1: "overcome", v2: "overcame", v3: "overcome", arti: "mengatasi" },
  { v1: "sew", v2: "sewed", v3: "sewn/sewed", arti: "menjahit" },
  { v1: "shrink", v2: "shrank", v3: "shrunk", arti: "menyusut" },
  { v1: "slide", v2: "slid", v3: "slid", arti: "meluncur" },
  { v1: "sting", v2: "stung", v3: "stung", arti: "menyengat" },
  { v1: "stink", v2: "stank/stunk", v3: "stunk", arti: "berbau busuk" },
  { v1: "strike", v2: "struck", v3: "struck", arti: "memukul; menyerang" },
  { v1: "weep", v2: "wept", v3: "wept", arti: "menangis" },
  { v1: "kneel", v2: "knelt/kneeled", v3: "knelt/kneeled", arti: "berlutut" },
  { v1: "bear", v2: "bore", v3: "borne", arti: "menanggung; melahirkan" },
  { v1: "arise", v2: "arose", v3: "arisen", arti: "muncul; timbul" },
  { v1: "awake", v2: "awoke", v3: "awoken", arti: "bangun (dari tidur)" },
  { v1: "forbid", v2: "forbade", v3: "forbidden", arti: "melarang" },
  { v1: "sink", v2: "sank", v3: "sunk", arti: "tenggelam" },
  { v1: "spin", v2: "spun", v3: "spun", arti: "berputar; memintal" },
  { v1: "split", v2: "split", v3: "split", arti: "membelah; membagi" },
  { v1: "spoil", v2: "spoilt/spoiled", v3: "spoilt/spoiled", arti: "merusak; memanjakan" },
  { v1: "spill", v2: "spilt/spilled", v3: "spilt/spilled", arti: "menumpahkan" },
  { v1: "spell", v2: "spelt/spelled", v3: "spelt/spelled", arti: "mengeja" },
  { v1: "smell", v2: "smelt/smelled", v3: "smelt/smelled", arti: "mencium (bau)" },
  { v1: "bless", v2: "blessed/blest", v3: "blessed/blest", arti: "memberkati" },
  { v1: "dwell", v2: "dwelt/dwelled", v3: "dwelt/dwelled", arti: "tinggal; berdiam" },
  { v1: "weave", v2: "wove", v3: "woven", arti: "menenun" },
  { v1: "wring", v2: "wrung", v3: "wrung", arti: "memeras" },
  { v1: "sow", v2: "sowed", v3: "sown/sowed", arti: "menabur (benih)" },
  { v1: "mow", v2: "mowed", v3: "mown/mowed", arti: "memangkas (rumput)" },
  { v1: "saw", v2: "sawed", v3: "sawn/sawed", arti: "menggergaji" },
  { v1: "shed", v2: "shed", v3: "shed", arti: "menumpahkan; menggugurkan" },
  { v1: "slay", v2: "slew", v3: "slain", arti: "membantai; membunuh" },
  { v1: "spit", v2: "spat/spit", v3: "spat/spit", arti: "meludah" },
  { v1: "tread", v2: "trod", v3: "trodden/trod", arti: "menginjak" },
  { v1: "thrust", v2: "thrust", v3: "thrust", arti: "mendorong; menusuk" },
  { v1: "undertake", v2: "undertook", v3: "undertaken", arti: "melaksanakan; menyanggupi" },
  { v1: "withdraw", v2: "withdrew", v3: "withdrawn", arti: "menarik (diri/uang)" },
  { v1: "misunderstand", v2: "misunderstood", v3: "misunderstood", arti: "salah paham" },
  { v1: "rebuild", v2: "rebuilt", v3: "rebuilt", arti: "membangun kembali" },
  { v1: "repay", v2: "repaid", v3: "repaid", arti: "membayar kembali" },
  { v1: "oversleep", v2: "overslept", v3: "overslept", arti: "kesiangan" },
  { v1: "overhear", v2: "overheard", v3: "overheard", arti: "tak sengaja mendengar" },
  { v1: "foresee", v2: "foresaw", v3: "foreseen", arti: "memperkirakan" },
  { v1: "undergo", v2: "underwent", v3: "undergone", arti: "mengalami; menjalani" },
  { v1: "uphold", v2: "upheld", v3: "upheld", arti: "menegakkan; mempertahankan" },
  { v1: "withhold", v2: "withheld", v3: "withheld", arti: "menahan" },
  { v1: "withstand", v2: "withstood", v3: "withstood", arti: "menahan; bertahan menghadapi" },
  { v1: "forsake", v2: "forsook", v3: "forsaken", arti: "meninggalkan" },
  { v1: "stride", v2: "strode", v3: "stridden", arti: "melangkah lebar" },
  { v1: "strive", v2: "strove/strived", v3: "striven/strived", arti: "berjuang; berusaha keras" },
  { v1: "thrive", v2: "thrived/throve", v3: "thrived/thriven", arti: "berkembang pesat" },
  { v1: "swell", v2: "swelled", v3: "swollen/swelled", arti: "membengkak" },
  { v1: "wed", v2: "wed/wedded", v3: "wed/wedded", arti: "menikahi" },
  { v1: "wet", v2: "wet/wetted", v3: "wet/wetted", arti: "membasahi" },
  { v1: "fit", v2: "fit/fitted", v3: "fit/fitted", arti: "pas; cocok (ukuran)" },
  { v1: "input", v2: "input/inputted", v3: "input/inputted", arti: "memasukkan (data)" },
  { v1: "prove", v2: "proved", v3: "proven/proved", arti: "membuktikan" },
  { v1: "dive", v2: "dived/dove", v3: "dived", arti: "menyelam" },
  { v1: "shave", v2: "shaved", v3: "shaven/shaved", arti: "mencukur" },
  { v1: "shear", v2: "sheared", v3: "shorn/sheared", arti: "menggunting bulu" },
  { v1: "spring", v2: "sprang", v3: "sprung", arti: "melompat; memancar" },
  { v1: "behold", v2: "beheld", v3: "beheld", arti: "memandang" },
  { v1: "befall", v2: "befell", v3: "befallen", arti: "menimpa" },
  { v1: "forecast", v2: "forecast", v3: "forecast", arti: "meramalkan" },
  { v1: "foretell", v2: "foretold", v3: "foretold", arti: "meramalkan" },
  { v1: "mislead", v2: "misled", v3: "misled", arti: "menyesatkan" },
  { v1: "misread", v2: "misread", v3: "misread", arti: "salah membaca" },
  { v1: "mishear", v2: "misheard", v3: "misheard", arti: "salah dengar" },
  { v1: "overtake", v2: "overtook", v3: "overtaken", arti: "menyusul; mendahului" },
  { v1: "overthrow", v2: "overthrew", v3: "overthrown", arti: "menggulingkan" },
  { v1: "redo", v2: "redid", v3: "redone", arti: "mengulang; mengerjakan ulang" },
  { v1: "rewrite", v2: "rewrote", v3: "rewritten", arti: "menulis ulang" },
  { v1: "undo", v2: "undid", v3: "undone", arti: "membatalkan; membuka" },
  { v1: "unwind", v2: "unwound", v3: "unwound", arti: "bersantai; melepas lilitan" },
  { v1: "upset", v2: "upset", v3: "upset", arti: "membuat kesal; mengganggu" },
  { v1: "retell", v2: "retold", v3: "retold", arti: "menceritakan ulang" },
  { v1: "rethink", v2: "rethought", v3: "rethought", arti: "memikirkan ulang" },
  { v1: "remake", v2: "remade", v3: "remade", arti: "membuat ulang" },
  { v1: "retake", v2: "retook", v3: "retaken", arti: "mengambil ulang" },
  { v1: "overdo", v2: "overdid", v3: "overdone", arti: "berlebihan; melebih-lebihkan" },
  { v1: "overeat", v2: "overate", v3: "overeaten", arti: "makan berlebihan" },
  { v1: "disprove", v2: "disproved", v3: "disproven/disproved", arti: "menyanggah" },
  { v1: "resell", v2: "resold", v3: "resold", arti: "menjual kembali" },
  { v1: "ghostwrite", v2: "ghostwrote", v3: "ghostwritten", arti: "menulis untuk orang lain" },
  { v1: "handwrite", v2: "handwrote", v3: "handwritten", arti: "menulis tangan" },
  { v1: "proofread", v2: "proofread", v3: "proofread", arti: "mengoreksi naskah" },
  { v1: "abide", v2: "abode/abided", v3: "abode/abided", arti: "bertahan; mematuhi" },
  { v1: "alight", v2: "alit/alighted", v3: "alit/alighted", arti: "turun; hinggap" },
  { v1: "babysit", v2: "babysat", v3: "babysat", arti: "menjaga anak" },
  { v1: "backslide", v2: "backslid", v3: "backslid", arti: "kembali ke kebiasaan buruk" },
  { v1: "beget", v2: "begot", v3: "begotten", arti: "memperanakkan; menimbulkan" },
  { v1: "beseech", v2: "besought/beseeched", v3: "besought/beseeched", arti: "memohon" },
  { v1: "beset", v2: "beset", v3: "beset", arti: "mengganggu; mengepung" },
  { v1: "bespeak", v2: "bespoke", v3: "bespoken", arti: "memesan; menandakan" },
  { v1: "bestride", v2: "bestrode", v3: "bestridden", arti: "mengangkangi" },
  { v1: "betake", v2: "betook", v3: "betaken", arti: "pergi (ke)" },
  { v1: "bethink", v2: "bethought", v3: "bethought", arti: "merenungkan" },
  { v1: "bid", v2: "bid", v3: "bid", arti: "menawar" },
  { v1: "broadcast", v2: "broadcast", v3: "broadcast", arti: "menyiarkan" },
  { v1: "chide", v2: "chid/chided", v3: "chidden/chided", arti: "memarahi" },
  { v1: "clothe", v2: "clad/clothed", v3: "clad/clothed", arti: "memberi pakaian" },
  { v1: "crossbreed", v2: "crossbred", v3: "crossbred", arti: "mengawinsilangkan" },
  { v1: "deepfreeze", v2: "deepfroze", v3: "deepfrozen", arti: "membekukan" },
  { v1: "floodlight", v2: "floodlit", v3: "floodlit", arti: "menyinari (dengan lampu sorot)" },
  { v1: "forbear", v2: "forbore", v3: "forborne", arti: "menahan diri" },
  { v1: "forgo", v2: "forwent", v3: "forgone", arti: "merelakan; mengurungkan" },
  { v1: "gainsay", v2: "gainsaid", v3: "gainsaid", arti: "menyangkal" },
  { v1: "gild", v2: "gilt/gilded", v3: "gilt/gilded", arti: "menyepuh emas" },
  { v1: "gird", v2: "girt/girded", v3: "girt/girded", arti: "mengikatkan" },
  { v1: "hamstring", v2: "hamstrung", v3: "hamstrung", arti: "melumpuhkan" },
  { v1: "hew", v2: "hewed", v3: "hewn/hewed", arti: "menebang; memahat" },
  { v1: "inlay", v2: "inlaid", v3: "inlaid", arti: "menatah; menghias" },
  { v1: "interbreed", v2: "interbred", v3: "interbred", arti: "mengawinsilangkan" },
  { v1: "interweave", v2: "interwove", v3: "interwoven", arti: "menjalin" },
  { v1: "knit", v2: "knit/knitted", v3: "knit/knitted", arti: "merajut" },
  { v1: "lade", v2: "laded", v3: "laden", arti: "memuat" },
  { v1: "lip-read", v2: "lip-read", v3: "lip-read", arti: "membaca gerak bibir" },
  { v1: "miscast", v2: "miscast", v3: "miscast", arti: "salah memilih peran" },
  { v1: "misdeal", v2: "misdealt", v3: "misdealt", arti: "salah membagi (kartu)" },
  { v1: "misgive", v2: "misgave", v3: "misgiven", arti: "merasa khawatir" },
  { v1: "mishit", v2: "mishit", v3: "mishit", arti: "salah memukul" },
  { v1: "mislay", v2: "mislaid", v3: "mislaid", arti: "salah menaruh" },
  { v1: "misspell", v2: "misspelt/misspelled", v3: "misspelt/misspelled", arti: "salah mengeja" },
  { v1: "misspend", v2: "misspent", v3: "misspent", arti: "menyia-nyiakan" },
  { v1: "outbid", v2: "outbid", v3: "outbid", arti: "menawar lebih tinggi" },
  { v1: "outdo", v2: "outdid", v3: "outdone", arti: "melampaui; mengungguli" },
  { v1: "outdraw", v2: "outdrew", v3: "outdrawn", arti: "menarik lebih cepat" },
  { v1: "outfight", v2: "outfought", v3: "outfought", arti: "mengalahkan (dalam pertarungan)" },
  { v1: "outgrow", v2: "outgrew", v3: "outgrown", arti: "tumbuh melampaui" },
  { v1: "outlay", v2: "outlaid", v3: "outlaid", arti: "mengeluarkan (biaya)" },
  { v1: "outride", v2: "outrode", v3: "outridden", arti: "mengungguli (berkuda/berkendara)" },
  { v1: "outrun", v2: "outran", v3: "outrun", arti: "berlari lebih cepat" },
  { v1: "outsell", v2: "outsold", v3: "outsold", arti: "menjual lebih banyak" },
  { v1: "outshine", v2: "outshone", v3: "outshone", arti: "mengungguli; lebih cemerlang" },
  { v1: "outspend", v2: "outspent", v3: "outspent", arti: "membelanjakan lebih banyak" },
  { v1: "overbid", v2: "overbid", v3: "overbid", arti: "menawar berlebihan" },
  { v1: "overdraw", v2: "overdrew", v3: "overdrawn", arti: "menarik (uang) berlebihan" },
  { v1: "overlay", v2: "overlaid", v3: "overlaid", arti: "melapisi" },
  { v1: "overpay", v2: "overpaid", v3: "overpaid", arti: "membayar berlebih" },
  { v1: "override", v2: "overrode", v3: "overridden", arti: "mengesampingkan; membatalkan" },
  { v1: "overrun", v2: "overran", v3: "overrun", arti: "melampaui; menyerbu" },
  { v1: "oversee", v2: "oversaw", v3: "overseen", arti: "mengawasi" },
  { v1: "overwrite", v2: "overwrote", v3: "overwritten", arti: "menimpa (tulisan/berkas)" },
  { v1: "partake", v2: "partook", v3: "partaken", arti: "ikut serta" },
  { v1: "plead", v2: "pleaded/pled", v3: "pleaded/pled", arti: "memohon; membela diri" },
  { v1: "prepay", v2: "prepaid", v3: "prepaid", arti: "membayar di muka" },
  { v1: "rebind", v2: "rebound", v3: "rebound", arti: "menjilid ulang" },
  { v1: "recast", v2: "recast", v3: "recast", arti: "menyusun ulang; mengganti pemeran" },
  { v1: "redraw", v2: "redrew", v3: "redrawn", arti: "menggambar ulang" },
  { v1: "relay", v2: "relaid", v3: "relaid", arti: "memasang ulang" },
  { v1: "reset", v2: "reset", v3: "reset", arti: "mengatur ulang" },
  { v1: "resit", v2: "resat", v3: "resat", arti: "mengulang ujian" },
  { v1: "rewind", v2: "rewound", v3: "rewound", arti: "memutar balik" },
  { v1: "rid", v2: "rid", v3: "rid", arti: "menyingkirkan; membersihkan" },
  { v1: "sightread", v2: "sightread", v3: "sightread", arti: "membaca not (langsung memainkan)" },
  { v1: "sling", v2: "slung", v3: "slung", arti: "melemparkan" },
  { v1: "slink", v2: "slunk", v3: "slunk", arti: "mengendap-endap" },
  { v1: "slit", v2: "slit", v3: "slit", arti: "menyayat" },
  { v1: "smite", v2: "smote", v3: "smitten", arti: "menghantam" },
  { v1: "speed", v2: "sped/speeded", v3: "sped/speeded", arti: "melaju cepat" },
  { v1: "spellbind", v2: "spellbound", v3: "spellbound", arti: "memikat; menyihir" },
  { v1: "spotlight", v2: "spotlit/spotlighted", v3: "spotlit/spotlighted", arti: "menyoroti" },
  { v1: "strew", v2: "strewed", v3: "strewn/strewed", arti: "menaburkan" },
  { v1: "string", v2: "strung", v3: "strung", arti: "merangkai; memasang tali" },
  { v1: "sublet", v2: "sublet", v3: "sublet", arti: "menyewakan kembali" },
  { v1: "sunburn", v2: "sunburnt/sunburned", v3: "sunburnt/sunburned", arti: "terbakar sinar matahari" },
  { v1: "telecast", v2: "telecast", v3: "telecast", arti: "menyiarkan (televisi)" },
  { v1: "typecast", v2: "typecast", v3: "typecast", arti: "menetapkan peran khas" },
  { v1: "typeset", v2: "typeset", v3: "typeset", arti: "menyusun huruf cetak" },
  { v1: "typewrite", v2: "typewrote", v3: "typewritten", arti: "mengetik" },
  { v1: "unbend", v2: "unbent", v3: "unbent", arti: "meluruskan" },
  { v1: "unbind", v2: "unbound", v3: "unbound", arti: "melepaskan ikatan" },
  { v1: "undercut", v2: "undercut", v3: "undercut", arti: "menjual lebih murah" },
  { v1: "underlie", v2: "underlay", v3: "underlain", arti: "mendasari" },
  { v1: "underpay", v2: "underpaid", v3: "underpaid", arti: "membayar terlalu rendah" },
  { v1: "undersell", v2: "undersold", v3: "undersold", arti: "menjual lebih murah" },
  { v1: "undershoot", v2: "undershot", v3: "undershot", arti: "meleset ke bawah; kurang dari target" },
  { v1: "underspend", v2: "underspent", v3: "underspent", arti: "membelanjakan terlalu sedikit" },
  { v1: "underwrite", v2: "underwrote", v3: "underwritten", arti: "menjamin (asuransi)" },
  { v1: "unfreeze", v2: "unfroze", v3: "unfrozen", arti: "mencairkan" },
  { v1: "unlearn", v2: "unlearnt/unlearned", v3: "unlearnt/unlearned", arti: "melupakan (yang dipelajari)" },
  { v1: "unsay", v2: "unsaid", v3: "unsaid", arti: "menarik kembali ucapan" },
  { v1: "unstick", v2: "unstuck", v3: "unstuck", arti: "melepaskan (yang menempel)" },
  { v1: "unstring", v2: "unstrung", v3: "unstrung", arti: "melepas tali/senar" },
  { v1: "unteach", v2: "untaught", v3: "untaught", arti: "mengajari hal sebaliknya" },
  { v1: "waylay", v2: "waylaid", v3: "waylaid", arti: "menghadang" },
  { v1: "wreak", v2: "wreaked/wrought", v3: "wreaked/wrought", arti: "menimbulkan (kerusakan)" }
];

// Ekspor sederhana untuk dipakai global oleh halaman.
if (typeof window !== 'undefined') { window.IRREGULAR_VERBS = IRREGULAR_VERBS; }
